Repository jenkinsci/bom, pull requests merged in 2019-08, with the labels that each got.

#37 structs-plugin.version=1.20
  bom/pom.xml
  pct.sh
Labels: dependencies

#39 2.150.x merge from master
  Jenkinsfile
  README.md
  bom/pom.xml
  local-test.sh
  pct.sh
  pom.xml
  sample-plugin/pom.xml
Labels: chore

#40 2.138.x merge
  Jenkinsfile
  README.md
  bom/pom.xml
  local-test.sh
  pct.sh
  pom.xml
  sample-plugin/pom.xml
Labels: chore

#60 Add ansicolor and timestamper to the managed set
  bom/pom.xml
  pct.sh
  sample-plugin/pom.xml
Labels: enhancement

#70 Bump workflow-job from 2.33 to 2.34
  bom/pom.xml
Labels: dependencies

#53 Add more plugins to the managed set
  bom/pom.xml
  pct.sh
  sample-plugin/pom.xml
Labels: enhancement
