Repository jenkinsci/bom, pull requests merged in 2020-07, with the labels that each got.

#264 Add workflow-job tests jar to bom
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#266 Filter dependabot to only latest line and sample plugin
  .dependabot/config.yml
  .github/dependabot.yml
Labels: chore

#270 Add HTML Publisher to the managed set
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#287 Bump ssh-credentials to version that has jcasc test harness fix
  bom-2.176.x/pom.xml
Labels: chore

#277 Detect overall PCT failures
  pct.sh
Labels: tests

#282 Add jackson2-api
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#281 Add pipeline-stage-step
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: enhancement
