Repository jenkinsci/bom, pull requests merged in 2020-04, with the labels that each got.

#172 Bump configuration-as-code from 1.34 to 1.35
  .gitignore
  bom-latest/pom.xml
  local-test.sh
  pct.sh
  prep.sh
  sample-plugin/pom.xml
Labels: dependencies

#110 Adding 2.190.x line
  README.md
  bom-2.176.x/pom.xml
  bom-latest/pom.xml
  pct.sh
  pom.xml
  prep.sh
  sample-plugin/pom.xml
Labels: enhancement

#213 Flaky CI builds
  Jenkinsfile
  pct.sh
  prep.sh
Labels: chore

#222 Add 2.222.x & 2.204.x, remove 2.150.x
  bom-2.190.x/pom.xml
  bom-2.204.x/pom.xml
  bom-latest/pom.xml
  pct.sh
  pom.xml
  prep.sh
  sample-plugin/check.groovy
  sample-plugin/pom.xml
Labels: breaking

#226 Update to 4.0 parent pom
  sample-plugin/pom.xml
Labels: dependencies

#231 README: Update title to be explicit that this BOM is for plugins
  README.md
Labels: documentation
