Repository jenkinsci/bom, pull requests merged in 2020-10, with the labels that each got.

#315 Changing CasC in 2.204 to use a prop
  bom-2.204.x/pom.xml
Labels: bug

#316 Force rerunFailingTestsCount=4 in PCT
  Jenkinsfile
Labels: chore

#319 Turn off throttling, and turn back on incrementals publishing
  Jenkinsfile
Labels: chore

#334 Test against 2.249.2
  sample-plugin/pom.xml
Labels: chore

#339 Adding 2.263.x line
  Jenkinsfile
  bom-2.249.x/pom.xml
  bom-latest/pom.xml
  pct.sh
  pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#341 Ignore failures in InjectedTest
  pct.sh
Labels: tests

#338 Add modern UI plugins, checks-api, update junit, remove 2.176.x & 2.190.x
  Jenkinsfile
  bom-2.176.x/pom.xml
  bom-2.190.x/pom.xml
  bom-2.204.x/pom.xml
  bom-latest/pom.xml
  pom.xml
  sample-plugin/pom.xml
Labels: dependencies, enhancement, removed
