Repository jenkinsci/bom, pull requests merged in 2020-01, with the labels that each got.

#148 GitAPITestCase.test_addSubmodule fails in PCT
  pct.sh
Labels: tests

#147 Removed 2.138.x line
  README.md
  bom-2.138.x/pom.xml
  pct.sh
  pom.xml
  sample-plugin/pom.xml
Labels: removed

#150 Suppressing ConfigurationAsCodeTest failures
  pct.sh
Labels: chore

#161 Bump configuration-as-code from 1.34 to 1.35
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: breaking

#163 Bump up PCT
  pct.sh
  prep.sh
Labels: dependencies

#164 Revert "Bump configuration-as-code from 1.34 to 1.35 (test harness renamed)"
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: dependencies
