Repository jenkinsci/bom, pull requests merged in 2021-07, with the labels that each got.

#591 Bump pipeline-model-definition to v1.9.1
  bom-latest/pom.xml
Labels: dependencies

#587 Retire bom-2.222.x
  README.md
  bom-2.222.x/pom.xml
  pom.xml
  sample-plugin/pom.xml
Labels: breaking

#592 Ignoring `BourneShellScriptTest` for now, as it causes a significant number of runs to fail
  Jenkinsfile
  pct.sh
Labels: chore

#595 Ignore BasicModelDefTest
  pct.sh
Labels: chore

#582 Initialize new LTS line (2.302)
  bom-2.289.x/pom.xml
  bom-latest/pom.xml
  pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#597 Skip marking build unstable if we are going to attempt again on a new node
  Jenkinsfile
Labels: chore

#596 Ignore `MatrixTest`
  pct.sh
Labels: chore

#594 Update pipeline model definition on all lines
  bom-2.277.x/pom.xml
Labels: dependencies

#581 Bump `jackson2-api` from 2.12.3 to 2.12.4
  bom-latest/pom.xml
Labels: enhancement

#610 Use `surefire.excludesFile` to skip failing tests
  Jenkinsfile
  excludes.txt
  local-test.sh
  pct.sh
Labels: tests

#609 Retire 2.235
  bom-2.235.x/pom.xml
  excludes.txt
  pom.xml
  sample-plugin/pom.xml
Labels: removed
