Repository jenkinsci/bom, pull requests merged in 2021-06, with the labels that each got.

#531 Bump parent pom
  pom.xml
Labels: dependencies

#511 Initialize new LTS line (2.289)
  bom-2.277.x/pom.xml
  bom-latest/pom.xml
  failFast
  pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#541 Restore `failFast` to `true`
  failFast
Labels: chore

#550 Add Subversion to the managed set
  bom-latest/pom.xml
  pct.sh
  sample-plugin/pom.xml
Labels: enhancement

#554 Add Subversion tests to managed set
  bom-latest/pom.xml
Labels: enhancement

#472 Add Rebuilder to the managed set
  bom-latest/pom.xml
  pct.sh
  sample-plugin/pom.xml
Labels: chore

#471 Add Throttle Concurrent Builds to the managed set
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: chore

#555 Bump Throttle Concurrent Builds from 2.2 to 2.3
  bom-latest/pom.xml
Labels: dependencies

#556 Add Bouncy Castle API to the managed set
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: chore

#558 Increment subversion to 2.14.4
  bom-latest/pom.xml
Labels: dependencies

#565 Bump `workflow-multibranch` from 2.24 to 2.26
  bom-2.263.x/pom.xml
  bom-latest/pom.xml
Labels: dependencies

#553 Add Pipeline Graph Analysis to the managed set
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: dependencies

#473 Add Workspace Cleanup and Resource Disposer to the managed set
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: enhancement
