Repository jenkinsci/bom, pull requests merged in 2021-09, with the labels that each got.

#639 Exclude git client plugin test_list_branches failures
  excludes.txt
Labels: tests

#642 Add Pipeline Utility Steps to the managed set
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#651 Ignore failing git plugin Assembla test
  excludes.txt
Labels: tests

#656 More flakey declarative pipeline tests
  excludes.txt
Labels: chore
