Repository jenkinsci/bom, pull requests merged in 2021-05, with the labels that each got.

#505 Add caffeine-api
  bom-latest/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#506 Use 2.277.4 in sample plugin
  sample-plugin/pom.xml
Labels: dependencies

#507 Remove caffeine from sample plugin
  sample-plugin/pom.xml
Labels: chore

#508 [JEP-229] Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
  .mvn/maven.config
  README.md
  bom-2.222.x/pom.xml
  bom-2.235.x/pom.xml
  bom-2.249.x/pom.xml
  bom-2.263.x/pom.xml
  bom-latest/pom.xml
  pom.xml
  sample-plugin/pom.xml
Labels: chore

#524 Re-enabling some previously excluded tests that should have been fixed and released by now
  pct.sh
Labels: tests
