Repository jenkinsci/bom, pull requests merged in 2022-01, with the labels that each got.

#810 Remove exclusions that are no longer needed
  excludes.txt
Labels: skip-changelog

#814 Update root versions
  .mvn/extensions.xml
  pom.xml
Labels: dependencies

#813 Add tests of `plugin-util` to BOM
  bom-weekly/pom.xml
Labels: tests

#822 Update `workflow-multibranch` to `704.v8f039a_e2e8cf`; `JobPropertyStepTest` now passes
  bom-weekly/pom.xml
  excludes.txt
Labels: dependencies

#847 Remove unnecessary exclusion
  excludes.txt
Labels: skip-changelog

#853 Remove `WorkflowRunRestartTest` exclusion
  excludes.txt
Labels: chore

#867 Remove `htmlpublisher` hack
  sample-plugin/pom.xml
Labels: skip-changelog
