Repository jenkinsci/bom, pull requests merged in 2022-06, with the labels that each got.

#1187 [JENKINS-67164] Plugin updates related to `FlowExecutionList` changes
  bom-2.319.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies

#1198 use reusable workflow for maven cd
  .github/workflows/cd.yaml
Labels: chore

#1206 Sort entries in pom.xml files
  bom-2.303.x/pom.xml
  bom-2.319.x/pom.xml
Labels: skip-changelog

#1205 Add support for forensics-api
  bom-2.303.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#1209 Bump version of data-tables-api to 1.12.1-1
  bom-2.303.x/pom.xml
  bom-weekly/pom.xml
Labels: enhancement

#1217 chore: Bump 2.346 profile to .1 and bump 2.332 to .4
  sample-plugin/pom.xml
Labels: enhancement

#1223 Bump junit from 1.53 to 1.53.0.1 in 2.289.x
  bom-2.289.x/pom.xml
Labels: dependencies

#1215 Adding mina-sshd-api core and commons
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement
