Repository jenkinsci/bom, pull requests merged in 2022-04, with the labels that each got.

#977 Adding `jjwt-api`
  README.md
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#981 Use major version
  .github/workflows/cd.yaml
Labels: skip-changelog

#988 Test against new LTS 2.332.2
  sample-plugin/pom.xml
Labels: dependencies

#998 Sort POM entries and remove duplicates
  bom-2.319.x/pom.xml
  bom-2.332.x/pom.xml
Labels: skip-changelog

#1016 Restore `support-core` to plugin BOM
  bom-2.319.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: bug, dependencies, java

#1020 Add/update GitLab plugins
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#1084 Test on Java 17
  Jenkinsfile
  pct.sh
Labels: enhancement

#1086 Check both Surefire and Failsafe reports
  pct.sh
Labels: bug

#1092 Bump Java JSON Web Token (JJWT) from 0.11.2-9.c8b45b8bb173 to 0.11.2-71.v2722b_b_06a_2a_f
  bom-weekly/pom.xml
Labels: dependencies, java

#1093 Support multi-module projects
  pct.sh
Labels: tests
