Repository jenkinsci/bom, pull requests merged in 2022-05, with the labels that each got.

#1102 Test against LTS 2.332.3
  sample-plugin/pom.xml
Labels: dependencies

#571 Bump versions of JS UI plugins to latest version
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: dependencies, java

#1097 Add Config File Provider to the managed set
  bom-2.289.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#1107 Remove no-longer-needed exclusion
  sample-plugin/pom.xml
Labels: skip-changelog

#1119 Adding `ssh-agent`
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#1118 `Jenkinsfile` simplifications
  Jenkinsfile
Labels: chore

#1131 Add pull request section to updatecli weekly
  updatecli/updatecli.d/weekly.yaml
Labels: chore

#1134 Refining micro versions in `sample-plugin` profiles
  sample-plugin/pom.xml
Labels: tests

#1148 Execute bash from path in she-bang
  local-test.sh
  pct.sh
  prep.sh
  updatecli/updatecli.d/update-plugins.sh
  updatecli/updatecli.d/weekly-apply.sh
Labels: chore

#1168 Add `pipeline-groovy-lib`
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement
