Repository jenkinsci/bom, pull requests merged in 2022-07, with the labels that each got.

#1243 remove check for rebuild and cloudbees-folder
  Jenkinsfile
Labels: chore

#1249 [JENKINS-49707] Retry `node` block after infrastructure outages
  Jenkinsfile
Labels: chore

#1256 Update `workflow-cps` & `workflow-job` in 2.346.x+ for icon-related changes
  bom-2.332.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies

#1270 Bump `workflow-job` and `matrix-project` in `bom-weekly`
  bom-2.346.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies

#1274 Clarifying use of `bom-weekly`
  README.md
Labels: documentation

#1280 Adapt to Jakarta Mail migration
  bom-2.319.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: dependencies, java

#1279 simplify updatecli pinned and add 2.346.x however pinned to .1
  .github/workflows/action-updatecli.yaml
  updatecli/updatecli.d/update-plugins.ps1
  updatecli/updatecli.d/update-plugins.sh
  updatecli/updatecli.d/update-plugins.yaml
Labels: chore

#1288 Adapt to Mail/Activation baseline bumps
  bom-2.319.x/pom.xml
  bom-weekly/pom.xml
Labels: enhancement, dependencies, java

#1298 [JENKINS-49707] Bumps related to `retry` without `conditions`
  bom-2.332.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies

#1321 Remove unnecessary exclusion
  excludes.txt
Labels: skip-changelog

#1324 skip dependencies for weekly and support property expansion for version
  updatecli/generate-manifests.ps1
Labels: chore

#1328 use pr title for auto merge
  updatecli/generate-manifests.ps1
Labels: chore

#1336 [JENKINS-45047] Migrate from PCT `org.jenkins.tools.test.hook.TransformPom` to HPI plugin `overrideWar`
  pct.sh
  prep.sh
Labels: enhancement

#1344 updatecli: Handle updating jenkins property version without guesswork
  .github/workflows/action-updatecli.yaml
  .gitignore
  updatecli/generate-manifests.ps1
  updatecli/update-jenkins.ps1
  updatecli/update-plugin.ps1
Labels: chore

#1345 Bump Maven HPI plugin from 3.30 to 3.31
  pct.sh
Labels: dependencies, java

#1351 Upgrade Plain Credentials from 1.8 to 139.ved2b_9cf7587b
  bom-weekly/pom.xml
  pct.sh
Labels: dependencies, java

#958 Add jnr-posix-api to the managed set
  bom-2.332.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#1355 Exclude `HttpRequestStepRoundTripTest`
  excludes.txt
Labels: skip-changelog

#1359 Exclude `TriggersTest`
  excludes.txt
Labels: skip-changelog
