Repository jenkinsci/bom, pull requests merged in 2022-08, with the labels that each got.

#1381 Backport of `ClassCastException` fix for JDK 11u16
  bom-2.319.x/pom.xml
Labels: dependencies

#1379 [JENKINS-69229] Revert `trilead-api` update
  .github/dependabot.yml
  bom-weekly/pom.xml
Labels: dependencies

#1383 Miscellaneous cleanup
  pct.sh
  prep.sh
Labels: skip-changelog

#1387 Initiate new LTS baseline 2.361.x
  bom-2.346.x/pom.xml
  bom-2.361.x/pom.xml
  pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#1386 Add `pam-auth` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: skip-changelog

#1392 Add `javadoc` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: dependencies, java

#1399 Upgrade toolchain
  pct.sh
  prep.sh
Labels: internal

#1385 Add `copyartifact` to the managed set
  Jenkinsfile
  bom-weekly/pom.xml
  pct.sh
  sample-plugin/pom.xml
Labels: enhancement

#1408 Upgrade parent POM from 1.70 to 1.85
  pom.xml
Labels: dependencies, java

#1422 Update `workflow-support`
  bom-weekly/pom.xml
Labels: developer
