Repository jenkinsci/bom, pull requests merged in 2022-10, with the labels that each got.

#1476 Freeze versions of JS plug-ins for Jenkins 2.332.x
  bom-2.332.x/pom.xml
Labels: dependencies

#1481 Bump commons-text-api to 1.10.0
  bom-weekly/pom.xml
Labels: developer

#1484 [JENKINS-69229] Use newer `trilead-api` on Java 11+ lines
  .github/dependabot.yml
  bom-2.346.x/pom.xml
  bom-weekly/pom.xml
  excludes.txt
Labels: dependencies

#1507 Update plugins related to 2022-10-19 security advisory; add `ionicons-api`
  bom-2.319.x/pom.xml
  bom-2.332.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/check.groovy
Labels: enhancement
