Repository jenkinsci/bom, pull requests merged in 2022-11, with the labels that each got.

#1544 Remove joda-time dependencyManagement
  sample-plugin/pom.xml
Labels: chore

#1543 Drop 2.319.x
  bom-2.319.x/pom.xml
  bom-2.332.x/pom.xml
  bom-2.346.x/pom.xml
  pct.sh
  pom.xml
  sample-plugin/check.groovy
  sample-plugin/pom.xml
Labels: breaking

#1541 Remove git client plugin test exclusions
  bom-2.332.x/pom.xml
  bom-weekly/pom.xml
  excludes.txt
Labels: dependencies

#1556 Disable `updatecli` on plugins
  updatecli/update-plugin.ps1
Labels: chore

#1553 Update workflow-cps, antisamy-markup-formatter, and the PCT
  bom-weekly/pom.xml
  prep.sh
Labels: dependencies

#1568 Remove redundant 2.332.x credentials dependency
  bom-2.332.x/pom.xml
Labels: chore

#1575 Bump `cloudbees-folder` only in `bom-weekly`
  bom-2.361.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies

#1585 Update versions after 2022-11-15 security release
  bom-2.332.x/pom.xml
  bom-weekly/pom.xml
Labels: developer

#1593 Control test behavior via `full-test` PR label
  Jenkinsfile
  README.md
  failFast
Labels: chore

#1606 Adapt to removal of Commons HttpClient 3.x
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: developer

#1612 Test against 2.375.1
  sample-plugin/pom.xml
Labels: tests, full-test
