Repository jenkinsci/bom, pull requests merged in 2022-03, with the labels that each got.

#644 Add `support-core` to the managed set
  bom-2.303.x/pom.xml
  bom-2.319.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#909 Add Pipeline: Milestone Step to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#927 Test against new LTS 2.332.1
  sample-plugin/pom.xml
Labels: enhancement, dependencies

#929 Add `file-parameters` to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#936 Remove unneeded exclusions
  excludes.txt
Labels: tests

#938 Sort `weekly` at top of reverse-chrono `lines.txt`
  prep.sh
Labels: tests

#950 Make shell scripts `shfmt(1)` and `shellcheck(1)` clean
  Jenkinsfile
  local-test.sh
  pct.sh
  prep.sh
  updatecli/updatecli.d/weekly-apply.sh
Labels: skip-changelog

#952 Indent here-documents in a natural fashion
  pct.sh
Labels: skip-changelog

#957 Use Eclipse Temurin, not AdoptOpenJDK, in CD action
  .github/workflows/cd.yaml
Labels: chore

#970 Update `credentials`
  bom-2.332.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies
