Repository jenkinsci/bom, pull requests merged in 2022-12, with the labels that each got.

#1615 Upgrade HPI plugin from 3.33 to 3.37
  pct.sh
Labels: tests

#1632 Update `text-finder` and `ws-cleanup` to latest
  bom-2.346.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies

#1634 Upgrade HPI plugin from 3.37 to 3.38
  pct.sh
Labels: dependencies

#1642 Bump plugin parent POM from 4.51 to 4.53 in `/sample-plugin`
  sample-plugin/pom.xml
Labels: dependencies

#1643 Pin git client plugin 3.12.4 for Jenkins 2.332.x tests
  bom-2.332.x/pom.xml
Labels: enhancement

#1513 Bump versions forensics-api, plugin-util-api, and checks-api
  bom-weekly/pom.xml
Labels: developer

#1663 Use git plugin 5.0.0 and git client plugin 4.0.0
  bom-2.346.x/pom.xml
  bom-weekly/pom.xml
Labels: developer
