Repository jenkinsci/bom, pull requests merged in 2023-11, with the labels that each got.

#2635 Document older version numbers and why they might be used
  README.md
Labels: documentation

#2646 Reduce `io.jenkins.blueocean.service.embedded.PipelineApiTest` exclusions
  excludes.txt
Labels: chore

#2644 Allow weekly release to be tested in isolation
  Jenkinsfile
  README.md
Labels: chore

#2648 Add appropriate labels from Renovate PRs
  .github/renovate.json
  sample-plugin/pom.xml
Labels: tests

#2651 Add Pipeline Maven Integration to the managed set
  bom-weekly/pom.xml
  pct.sh
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2657 Rely on release run instead of a weekly full
  .github/workflows/run-full-test.yaml
Labels: chore

#2663 Use Jenkins 2.426.1 as baseline for bom-2.426.x
  README.md
  sample-plugin/pom.xml
Labels: chore

#2655 Add some database plugins to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2682 Avoid data-tables, echarts, and prism upper bounds error
  pct.sh
Labels: chore

#2689 Bump configuration as code from 1738.v2d8b_a_b_8a_54b_1 to 1746.vf1673cfe690a
  bom-weekly/pom.xml
Labels: dependencies

#2691 Block GitHub API 1.318-461 due to GitHub branch source test failures
  .github/dependabot.yml
  bom-weekly/pom.xml
Labels: bug

#2694 Revert "Block GitHub API 1.318-461 due to GitHub branch source test failures"
  .github/dependabot.yml
  bom-weekly/pom.xml
Labels: weekly-test
