Repository jenkinsci/bom, pull requests merged in 2023-03, with the labels that each got.

#1825 Add `apache-httpcomponents-client-5-api` to bom
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#1842 Set `maven.repo.local` inside `WORKSPACE_TMP` in CI
  Jenkinsfile
  prep.sh
Labels: chore

#1892 Add GitHub Branch Source to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: developer

#1889 Add JaCoCo to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: developer

#1896 Update several plugins related to warnings-ng
  bom-weekly/pom.xml
Labels: dependencies

#1897 Add missing Mina SSHD plugins to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: developer

#1914 Record Launchable test results without a build
  Jenkinsfile
Labels: skip-artifact-caching-proxy
