Repository jenkinsci/bom, pull requests merged in 2023-06, with the labels that each got.

#2166 Honor a `full-test` marker file in addition to label
  Jenkinsfile
  README.md
Labels: chore

#2168 Use email-ext 2.98 and revert commit 2ed8f3a
  bom-weekly/pom.xml
  excludes.txt
Labels: dependencies

#2171 Retry tasks up to 6 times
  Jenkinsfile
Labels: chore

#2191 Add docker java API plugin to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: developer

#2201 Exclude failing tests pending release
  excludes.txt
Labels: tests

#2209 Exclude a git client maintenance test
  excludes.txt
Labels: chore

#2218 Remove 2.375.x support
  bom-2.375.x/pom.xml
  excludes.txt
  pom.xml
  sample-plugin/pom.xml
Labels: breaking, full-test

#2227 Add test JARs to the managed set
  README.md
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#2226 Add `external-monitor-job` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2189 Add `authentication-tokens` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2223 Add `run-condition` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2222 Add `parameterized-trigger` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2234 Test with Java 17 unconditionally
  Jenkinsfile
Labels: internal, full-test
