Repository jenkinsci/bom, pull requests merged in 2023-02, with the labels that each got.

#1738 Do not allow empty results
  Jenkinsfile
  pct.sh
Labels: chore

#1740 Remove deprecated `workflow-cps-global-lib` from BOM
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: removed

#1742 Use 'chore' label for pct version updates
  updatecli/updatecli.d/plugin-compat-tester.yml
Labels: chore

#1741 Use artifact caching proxy for BOM builds
  Jenkinsfile
Labels: chore

#1755 Fix #1739 - Remove bootstrap4 & popper api plugins
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: removed

#1760 Update plugins in 2023-02-15 security advisory
  bom-weekly/pom.xml
Labels: developer

#1770 [JENKINS-70528] Bump `workflow-durable-task-step` and `workflow-basic-steps` together
  bom-weekly/pom.xml
Labels: dependencies

#1788 Remove workaround for github plugin test failure
  Jenkinsfile
Labels: skip-changelog

#1764 Adapt to jenkinsci/plugin-compat-tester#462
  pct.sh
Labels: chore

#1792 Remove `-Denforcer.skip=true`
  pct.sh
Labels: chore
