Repository jenkinsci/bom, pull requests merged in 2023-09, with the labels that each got.

#2417 Add Kubernetes plugins to the managed set
  bom-2.387.x/pom.xml
  bom-weekly/pom.xml
  excludes.txt
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2435 Add BitBucket plugins to the managed set
  bom-2.387.x/pom.xml
  bom-weekly/pom.xml
  excludes.txt
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2441 Add Jenkins Advisor and Secure Requester plugins to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2455 Give `io.jenkins.tools.bom.sample.ExampleStepTest` enough memory to pass
  .mvn/extensions.xml
  .mvn/jvm.config
Labels: tests

#2456 Remove unnecessary exclusions
  sample-plugin/pom.xml
Labels: internal

#2457 Exclude specific test method rather than whole test
  excludes.txt
Labels: tests

#2466 Pin snakeyaml-api 1.33 for Jenkins 2.387.3
  bom-2.387.x/pom.xml
Labels: full-test

#2464 Add `docker-workflow` plugin to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2470 Don't declare sample plugin transitive dependencies
  sample-plugin/pom.xml
Labels: chore

#2475 Reduce Maven memory usage even more
  .mvn/jvm.config
Labels: skip-changelog

#2474 Add AWS Global Configuration to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2479 Exclude `RestartStageTest`
  excludes.txt
Labels: tests

#2490 Exclude `io.jenkins.blueocean.rest.impl.pipeline.RunImplTest`
  excludes.txt
Labels: tests

#2495 [JENKINS-71803] Blue Ocean tests fail on Java 21 with Mockito errors
  Jenkinsfile
Labels: tests

#2496 Disable parallelism in Blue Ocean test suite
  excludes.txt
  pct.sh
Labels: tests

#2498 Manage dependencies with Renovate instead of Updatecli
  .github/renovate.json
  .github/workflows/action-updatecli.yaml
  .gitignore
  prep-pct.sh
  updatecli/generate-manifests.ps1
  updatecli/update-jenkins.ps1
  updatecli/update-plugin.ps1
  updatecli/updatecli.d/plugin-compat-tester.yml
  updatecli/values.yaml
Labels: skip-changelog

#2502 Fix regex
  .github/renovate.json
Labels: skip-changelog

#2503 Handle theme upgrade
  bom-2.414.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies

#2514 Pin previous credentials-binding release for LTS profiles
  bom-2.414.x/pom.xml
Labels: full-test

#2440 Add Google plugins to the managed set
  Jenkinsfile
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#2545 Remove JENKINS-71804 workaround
  Jenkinsfile
Labels: tests

#2552 Revert to GitLab branch source 677.x for JCasC compatibility
  bom-weekly/pom.xml
Labels: bug
