Repository jenkinsci/bom, pull requests merged in 2023-01, with the labels that each got.

#1668 Dropping 2.332.x & 2.346.x
  .github/dependabot.yml
  README.md
  bom-2.332.x/pom.xml
  bom-2.346.x/pom.xml
  pom.xml
  sample-plugin/check.groovy
  sample-plugin/pom.xml
Labels: breaking, full-test

#1676 Add instance identity
  bom-weekly/pom.xml
Labels: developer

#1678 Upgrade PCT to latest
  prep.sh
Labels: dependencies

#1680 Upgrade PCT to latest
  prep.sh
Labels: dependencies

#1683 Upgrade PCT to latest
  pct.sh
  prep.sh
Labels: dependencies

#1706 Update versions after 2023-01-24 security release
  bom-weekly/pom.xml
Labels: developer
