Repository jenkinsci/bom, pull requests merged in 2023-08, with the labels that each got.

#2340 Add authorize project plugin to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: developer

#2221 Add `maven-plugin` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: work-in-progress, full-test

#2224 Add `conditional-buildstep` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#2308 Add Blue Ocean to the managed set
  bom-weekly/pom.xml
  excludes.txt
  sample-plugin/pom.xml
Labels: full-test

#2374 Update versions for fixes released in 2023-08-16 security advisory
  bom-weekly/pom.xml
Labels: dependencies

#2362 Test on Java 21
  Jenkinsfile
Labels: full-test

#2385 Add Cloud Statistics to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2392 Add aws-java-sdk-secretsmanager dependency
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#2399 Revert theme manager breakage
  bom-weekly/pom.xml
Labels: bug

#2408 Depend on 2.414.1 rather than 2.414
  sample-plugin/pom.xml
Labels: developer

#2415 Remove unnecessary workaround
  sample-plugin/check.groovy
Labels: skip-changelog

#2422 Add Active Directory, JUnit Realtime Test Reporter, Node Iterator API, and View Job Filters to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2418 Add AWS Credentials to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2434 Exclude memory-hogging Blue Ocean test
  excludes.txt
Labels: tests

#2445 Remove run-condition test failure workaround
  Jenkinsfile
Labels: full-test
