Repository jenkinsci/bom, pull requests merged in 2023-07, with the labels that each got.

#2238 Remove unnecessary workaround
  excludes.txt
Labels: tests

#2250 Remove explicit reviewers from Dependabot config
  .github/dependabot.yml
Labels: chore

#2220 Add `docker-commons` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2275 Exclude some config file provider tests temporarily
  excludes.txt
Labels: tests

#2278 Revert config file provider test exclusion
  excludes.txt
Labels: skip-changelog

#2292 Remove unnecessary exclusion
  excludes.txt
Labels: tests
