Repository jenkinsci/bom, pull requests merged in 2023-05, with the labels that each got.

#2033 chore(Jenkinsfile) minor optimization of the `withEnv` steps
  Jenkinsfile
Labels: chore

#2034 Skip PCT by default on PRs
  .github/workflows/dependabot-automerge.yaml
  .github/workflows/run-full-test.yaml
  Jenkinsfile
  README.md
  updatecli/updatecli.d/plugin-compat-tester.yml
Labels: chore, full-test

#2040 Squash Dependabot PRs
  .github/workflows/dependabot-automerge.yaml
Labels: chore

#2041 Set `NOT_BUILT` status on `master` with `BranchEventCause`
  Jenkinsfile
Labels: chore

#2048 Adding `CODEOWNERS`
  .github/CODEOWNERS
Labels: chore

#2047 Set Git user
  .github/workflows/run-full-test.yaml
Labels: chore

#2050 Drop `--reviewer`
  .github/workflows/run-full-test.yaml
Labels: chore

#2073 Update versions for fixes released in 2023-05-16 security advisory
  bom-weekly/pom.xml
Labels: dependencies

#2080 Remove use of Launchable shared library functionality
  Jenkinsfile
Labels: chore

#2085 Upgrade `sshd` from 3.275.v9e17c10f2571 to 3.303.vefc7119b_ec23
  bom-weekly/pom.xml
Labels: dependencies

#2114 Remove deprecated popper2 plugin from managed set
  bom-2.375.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: breaking

#2121 Remove 2.361.x support
  README.md
  bom-2.361.x/pom.xml
  pom.xml
  sample-plugin/pom.xml
Labels: breaking
