Repository jenkinsci/bom, pull requests merged in 2024-01, with the labels that each got.

#2810 Include ASM API plugin on bom
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#2817 Restore `script-security` updates
  .github/dependabot.yml
  README.md
  bom-weekly/pom.xml
  pct.sh
Labels: bug, weekly-test

#2851 Add MySQL and MariaDB database plugins
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: developer

#2887 When variable DOCKERIZED was set to 'false' then 'docker' section was executed
  local-test.sh
Labels: chore
