Repository jenkinsci/bom, pull requests merged in 2024-02, with the labels that each got.

#2904 Revert "Add flyway api plugin"
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: bug

#2912 Add flyway api plugin (docker tests now ignored)
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, weekly-test

#2922 [JENKINS-72613] `getItemName` changes
  bom-2.440.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies, weekly-test

#2940 Passing options to sample plugin build
  local-test.sh
Labels: internal

#2952 Revert "Bump `io.jenkins.plugins:plugin-util-api` from 3.8.0 to 4.1.0 in `/bom-weekly`"
  bom-2.414.x/pom.xml
  bom-weekly/pom.xml
Labels: bug

#2954 Update `plugin-util-api` and `prism-api`
  bom-2.414.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies, java

#2963 Add sqlserver-api plugin
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: developer
