Repository jenkinsci/bom, pull requests merged in 2024-08, with the labels that each got.

#3190 [JENKINS-73282] Run PCT with a Jetty 12 EE 8 test harness when core is Jetty 12 EE 8
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3480 Add commons-math3-api plugin
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: weekly-test

#3490 Add nodejs to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3494 Add Job DSL to the managed set
  bom-2.452.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3502 Add Promoted Builds to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3507 Add Build User Vars to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3508 Add Build Failure Analyzer to the managed set
  bom-weekly/pom.xml
  excludes.txt
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3516 Suppress accidental Build Failure Analyzer release
  .github/dependabot.yml
Labels: skip-changelog
