Repository jenkinsci/bom, pull requests merged in 2024-11, with the labels that each got.

#3885 Add Basic Branch Build Strategies to the managed set
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3886 Add Prometheus Metrics to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3889 Add EC2 to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3891 Add Git Parameter to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3919 Revert "Bump org.jenkins-ci.plugins:cloudbees-bitbucket-branch-source from 895.v15dc41668f03 to 906.vedf430cb_4481 in /bom-weekly"
  bom-2.452.x/pom.xml
  bom-weekly/pom.xml
Labels: skip-changelog

#3927 Changes the Release CRON for 2024-11-08 release
  Jenkinsfile
Labels: chore

#3931 Revert "Bump io.jenkins.plugins:artifact-manager-s3 from 878.v84f6f8f9dce7 to 886.v49a_e5d7857cc in /bom-weekly"
  bom-weekly/pom.xml
Labels: skip-changelog

#3943 Fixes Remove jenkinsci/jacoco-plugin#291 workaround #3921
  excludes.txt
Labels: tests, full-test

#3954 Revert "Bump org.jenkins-ci.plugins:badge from 2.4 to 2.5 in /bom-weekly"
  bom-weekly/pom.xml
Labels: skip-changelog

#3887 Incorporate CRON expression settings in release manager checklist
  CONTRIBUTING.md
  release-manager-scripts/bom-line-test.sh
  release-manager-scripts/bom-lock-master.sh
  release-manager-scripts/bom-release-issue-add-release-comment.sh
  release-manager-scripts/bom-release-issue-close.sh
  release-manager-scripts/bom-release-issue-create.sh
  release-manager-scripts/bom-release-issue-job-running.sh
  release-manager-scripts/bom-run-cd-workflow.sh
  release-manager-scripts/bom-test-all-lines.sh
  release-manager-scripts/bom-unlock-master.sh
Labels: documentation, skip-changelog

#3973 Schedule build to start at noon Denver time
  Jenkinsfile
Labels: chore

#3975 Pin htmlpublisher 1.36 for older lines
  bom-2.479.x/pom.xml
Labels: bug

#3986 Add Coverage to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3989 Add Locale to managed set
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4002 Add Parameter Separator to managed set
  bom-2.452.x/pom.xml
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4003 Add GitHub Checks to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4005 Add Parameterized Scheduler to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4007 Add SonarQube Scanner to the managed set
  bom-2.452.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4010 Add Azure SDK API to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4012 Add Azure Credentials to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4013 Add Git Forensics to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4014 Add Azure Storage to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4015 Add Azure VM Agents to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4016 Add Embeddable Build Status to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4017 Add Coverage Badges Extension to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4018 Add Pipeline GitHub to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4019 Add Generic Tool to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4022 Add Display URL for Blue Ocean to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4023 Add Flatpickr API to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4027 Add Artifactory Client API to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4031 add release lead calendar
  CONTRIBUTING.md
Labels: documentation, skip-changelog

#4030 Add Artifact Manager Artifactory to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4036 Pin ssh-credentials for 2.452.x
  bom-2.452.x/pom.xml
Labels: full-test

#4034 Add Amazon Web Services SDK 2 to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test
