Repository jenkinsci/bom, pull requests merged in 2024-07, with the labels that each got.

#3366 Update dependency `org.jenkins-ci.tests:plugins-compat-tester-cli` to v1479
  prep-pct.sh
Labels: skip-changelog

#3381 Revert "Bump org.jenkins-ci.plugins:htmlpublisher from 1.35 to 1.36 in /bom-weekly"
  bom-weekly/pom.xml
Labels: bug

#3390 Pin htmlpublisher 1.35 for 2.426.x
  bom-2.426.x/pom.xml
Labels: full-test

#3398 Revert "Bump org.jenkins-ci.plugins:ssh-credentials from 337.v395d2403ccd4 to 341.vf31377f30378 in /bom-weekly"
  bom-weekly/pom.xml
Labels: bug

#3404 Revert ssh-credentials 342.x
  bom-weekly/pom.xml
Labels: bug

#3374 Add 2.462.x release line, remove 2.426.x
  README.md
  bom-2.426.x/pom.xml
  bom-2.452.x/pom.xml
  bom-2.462.x/pom.xml
  pct.sh
  pom.xml
  sample-plugin/pom.xml
Labels: breaking, full-test
