Repository jenkinsci/bom, pull requests merged in 2024-03, with the labels that each got.

#2973 Revert "Bump org.jenkins-ci.plugins:credentials from 1319.v7eb_51b_3a_c97b_ to 1337.v60b_d7b_c7b_c9f in /bom-weekly"
  bom-2.414.x/pom.xml
  bom-weekly/pom.xml
Labels: bug

#2975 Add database-sqlserver
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: developer

#2964 Passing `SAMPLE_PLUGIN_OPTS` if already set
  local-test.sh
Labels: internal

#2980 Upgrade `jakarta-activation-api` and `jakarta-mail-api` to 2.1.3-1
  bom-weekly/pom.xml
Labels: dependencies, java

#3020 Fixes LTS version used for 2.440.x line
  sample-plugin/pom.xml
Labels: bug

#3021 Mailer 472.vf7c289a_4b_420 should be in bom-2.440.x
  bom-2.426.x/pom.xml
  bom-2.440.x/pom.xml
Labels: dependencies

#3047 Pick up new AWS Java SDK 1.12.671-445.ve02f9b_558f2e and its new modules
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#3054 Revert "Bump org.jenkins-ci.plugins:ssh-credentials from 322.v124df57ed808 to 326.v7fcb_a_ef6194b_ in /bom-weekly"
  bom-weekly/pom.xml
Labels: bug

#3057 Add `database-sqlite` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3079 Work around jenkins-infra/helpdesk#4021 on Artifact Caching Proxy (ACP)
  Jenkinsfile
Labels: bug
