Repository jenkinsci/bom, pull requests merged in 2024-09, with the labels that each got.

#3522 Revert "Bump io.jenkins.plugins:pipeline-graph-view from 313.v1322ce83d680 to 332.vb_232ced67fa_9 in /bom-weekly"
  bom-weekly/pom.xml
Labels: skip-changelog

#3521 Add CloudBees CD to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#2341 [JENKINS-73283] Run PCT with a Jetty 12 EE 9 test harness when core is Jetty 12 EE 9
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  excludes.txt
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3541 Revert "Bump jakarta.servlet:jakarta.servlet-api from 5.0.0 to 6.1.0 in /sample-plugin"
  .github/dependabot.yml
  sample-plugin/pom.xml
Labels: bug

#3550 Add Parallel Test Executor to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3544 Add OpenId Connect Authentication and Reverse Proxy Authentication to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, weekly-test

#3580 Revert `analysis-model-api` and `warnings-ng` upgrades
  bom-weekly/pom.xml
Labels: skip-changelog

#3589 Revert "Bump org.jenkins-ci.plugins:credentials from 1371.vfee6b_095f0a_3 to 1378.v81ef4269d764 in /bom-weekly"
  bom-weekly/pom.xml
Labels: skip-changelog

#3626 Update documentation for people maintaining the BOM
  CONTRIBUTING.md
  README.md
Labels: documentation, skip-changelog

#3627 Add Badge to the managed set #3607
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3634 Add Build Monitor to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test
