Repository jenkinsci/bom, pull requests merged in 2024-05, with the labels that each got.

#3169 Add byte-buddy api plugin
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#3200 Serialize Lockable Resources tests
  pct.sh
Labels: skip-changelog

#3232 Do not set the JTH War file
  pct.sh
Labels: chore, full-test

#3230 Introduce EdDSA-api plugin
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, weekly-test
