Repository jenkinsci/bom, pull requests merged in 2024-04, with the labels that each got.

#3090 Add markdown formatter plugin
  bom-2.414.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, weekly-test

#3103 Set JUnit check to be pending before maven build starts
  Jenkinsfile
Labels: chore

#3105 Revert "Work around jenkins-infra/helpdesk#4021 on Artifact Caching Proxy (ACP)"
  Jenkinsfile
Labels: weekly-test

#3094 Add `oidc-provider`
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, weekly-test

#3124 Document the version number of the last bom-2.401.x release
  README.md
Labels: documentation

#3123 Add 2.452.x line, remove 2.414.x line
  README.md
  bom-2.414.x/pom.xml
  bom-2.440.x/pom.xml
  bom-2.452.x/pom.xml
  pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3125 Document the final 2.414.x bom version
  README.md
Labels: documentation

#3127 Add Warnings to the managed set
  bom-weekly/pom.xml
  excludes.txt
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3137 Add Pipeline Graph View to the managed set
  bom-2.426.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3153 Adopt https://github.com/jenkinsci/lockable-resources-plugin/pull/653
  bom-2.426.x/pom.xml
  excludes.txt
Labels: chore
