Repository jenkinsci/bom, pull requests merged in 2024-12, with the labels that each got.

#4057 update release lead calendar
  CONTRIBUTING.md
Labels: skip-changelog

#4105 Apply developer label to dependency updates
  .github/dependabot.yml
Labels: chore

#4095 Pre-heat the artifact caching proxy
  Jenkinsfile
Labels: chore

#4117 Upgrade `aws-java-sdk2`
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: dependencies, java
