Repository jenkinsci/bom, pull requests merged in 2024-10, with the labels that each got.

#3671 Build fails when sorting plugins with uppercase artifact name
  sample-plugin/check.groovy
Labels: bug

#3677 Add 2.479.x release line, remove 2.440.x release line
  CONTRIBUTING.md
  README.md
  bom-2.440.x/pom.xml
  bom-2.462.x/pom.xml
  bom-2.479.x/pom.xml
  pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3690 Clean up after recent changes
  .github/dependabot.yml
  sample-plugin/pom.xml
Labels: skip-changelog

#3691 More cleanup after recent changes
  .github/dependabot.yml
  sample-plugin/pom.xml
Labels: skip-changelog

#3692 Add Jira Test Result Reporter to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#3706 Format `renovate.json`
  .github/renovate.json
Labels: skip-changelog

#3707 Migrate `renovate.json` to non-deprecated syntax
  .github/renovate.json
Labels: skip-changelog

#3729 Add emoji-symbols-api to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: weekly-test

#3743 Use gitlab plugin 1.8.2 in bom-2.462.x and earlier
  bom-2.462.x/pom.xml
Labels: dependencies

#3751 Add Groovy Postbuild plugin to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3791 Format shell scripts consistently in this repository
  local-test.sh
  release-manager-scripts/bom-get-branch-protection.sh
  release-manager-scripts/bom-line-test.sh
  release-manager-scripts/bom-lock-master.sh
  release-manager-scripts/bom-release-issue-add-release-comment.sh
  release-manager-scripts/bom-release-issue-close.sh
  release-manager-scripts/bom-release-issue-create.sh
  release-manager-scripts/bom-release-issue-job-running.sh
  release-manager-scripts/bom-test-all-lines.sh
  release-manager-scripts/bom-unlock-master.sh
Labels: skip-changelog

#3840 Fixes #3539 and #3537
  excludes.txt
Labels: full-test

#3843 Add Artifact Manager S3 to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3845 Add Google Cloud Platform SDK Storage to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3844 Add Build Timeout to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3851 Add CloudBees Disk Usage Simple to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3869 Revert script security 1367.x and workflow-cps 3975.x
  bom-weekly/pom.xml
Labels: bug, full-test

#3866 Use Jenkins 2.479.1 as bom-2.479.x base version
  sample-plugin/pom.xml
Labels: full-test

#3862 Add Versions Node Monitors to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#3890 New cron schedule for 2024-10-31 release
  Jenkinsfile
Labels: skip-changelog
