Repository jenkinsci/bom, pull requests merged in 2025-02, with the labels that each got.

#4375 Add Safe Restart to the managed set
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4376 Add GitLab Logo to the managed set
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4438 Bump `pipeline-input-step` from 508.v584c0e9a_2177 to 513.v7eb_fe7e2c0fc
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
Labels: dependencies, java, full-test

#4430 Add jsoup API plugin
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4472 Use docker-workflow 592.v1001d948426c, not 595.v60cec912059b_
  bom-weekly/pom.xml
Labels: weekly-test

#4473 Bump `org.jenkins-ci.plugins:docker-workflow` from 592.v1001d948426c to 596.v3e6972b_46b_e2 in `/bom-weekly`
  bom-weekly/pom.xml
Labels: dependencies, java, weekly-test

#4542 Update Launchable incremental
  prep.sh
Labels: skip-changelog
