Repository jenkinsci/bom, pull requests merged in 2025-06, with the labels that each got.

#5160 Only test newest and oldest lines to reduce costs
  Jenkinsfile
Labels: enhancement, full-test

#5168 Rotate release leads
  CONTRIBUTING.md
Labels: documentation

#5214 Add `aws-java-sdk2-sso` to BOM
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, weekly-test

#5249 Pin kubernetes plugins for 2.492.x due to kubernetes-credentials-provider
  bom-2.492.x/pom.xml
Labels: bug

#5254 Update BOM release lead rotation
  CONTRIBUTING.md
Labels: documentation
