Repository jenkinsci/bom, pull requests merged in 2025-01, with the labels that each got.

#4160 Pin `copyartifact` on older lines
  bom-2.479.x/pom.xml
Labels: bug

#4208 Update AWS SDK v2
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: dependencies, java

#4226 Add sbt to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4234 Revert versioncolumn 319.x upgrade
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
Labels: bug

#4238 Add instant-messaging to the managed set
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4239 Add Azure Key Vault to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4240 Use git client 5.0.2 in the 2.452.x and 2.462.x lines
  bom-2.462.x/pom.xml
  excludes.txt
Labels: bug

#4244 Add Design Library to the managed set
  bom-2.452.x/pom.xml
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4245 Add CloudBees File Leak Detector to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4249 Add Extra Tool Installers to the managed set
  bom-2.452.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4231 Add 2.492.x release line, remove 2.452.x release line
  CONTRIBUTING.md
  README.md
  bom-2.452.x/pom.xml
  bom-2.479.x/pom.xml
  bom-2.492.x/pom.xml
  pom.xml
  sample-plugin/pom.xml
Labels: enhancement, removed, full-test

#4254 Add Customizable Header to the managed set (fixes #4086)
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4297 Add Mercurial to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4301 Add Gitea to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4316 Add `aws-java-sdk2-cloudwatch` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4341 Add Email Extension Template to the managed set
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4342 Add Gitea Checks to the managed set
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4344 Remove duplicate locale plugin entry from 2.462.x line
  bom-2.462.x/pom.xml
Labels: chore

#4353 Update AWS Java SDK v2
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: dependencies, java

#4354 Add Naginator to the managed set
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4355 Add Skip Notifications Trait to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4356 Add Ignore Committer Strategy to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4357 Add SCM Skip to the managed set
  bom-2.462.x/pom.xml
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4358 Add Pipeline Multibranch build strategy extension to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement
