Repository jenkinsci/bom, pull requests merged in 2025-03, with the labels that each got.

#4650 Drop the 2.462.x line
  CONTRIBUTING.md
  README.md
  bom-2.462.x/pom.xml
  excludes.txt
  pom.xml
  sample-plugin/pom.xml
Labels: removed

#4673 Downgrade `jackson2-api`
  bom-weekly/pom.xml
Labels: bug

#4547 Remove unnecessary workaround
  sample-plugin/pom.xml
Labels: skip-changelog, weekly-test

#4669 chore(Jenkinsfile) introduce Maven client side caching
  Jenkinsfile
Labels: chore

#4641 Remove Jacoco plugin from BOM
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: developer, full-test

#4689 Test latest JTH on weekly line
  .github/renovate.json
  pct.sh
Labels: chore, full-test

#4701 Remove build-failure-analyzer-plugin#181 workaround
  excludes.txt
Labels: chore, full-test

#4704 Add jobcacher to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: full-test

#4705 Add URL Trigger to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4706 Add Docker plugin to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4711 Add Simple Theme to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4713 Add Swarm to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4715 Add Job Configuration History to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4716 Add Build Name Setter to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4717 Add Thin Backup to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4718 Add SSH Pipeline Steps to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4719 Add Ansible to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4720 Add PowerShell to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4725 Add Built On Column to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4726 Add Node and Label Parameter to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4727 Add `postbuild-task` to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, full-test

#4767 Add Job Import to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement

#4768 Add Extensible Choice Parameter to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, weekly-test

#4769 Add Build Timestamp to the managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement
