Repository jenkinsci/bom, pull requests merged in 2025-04, with the labels that each got.

#4840 Pin Mina on older lines
  bom-2.492.x/pom.xml
Labels: skip-changelog

#4883 Revert "chore(deps): bump io.jenkins.plugins:echarts-api from 5.6.0-2 to 5.6.0-3 in /bom-weekly"
  bom-weekly/pom.xml
Labels: skip-changelog

#4899 Upgrade Jackson from 2.17.0-391.vf90e272e0cf2 to 2.18.3-402.v74c4eb_f122b_2
  bom-weekly/pom.xml
Labels: developer, weekly-test

#4922 Revert "chore(deps): bump org.jenkins-ci.plugins:cloudbees-bitbucket-branch-source from 935.1.3 to 936.0.1 in /bom-weekly"
  bom-weekly/pom.xml
Labels: skip-changelog

#4975 Add Jobcacher S3 Storage Extension to managed set
  bom-weekly/pom.xml
  sample-plugin/pom.xml
Labels: enhancement, weekly-test

#4934 Add 2.504.x release line
  bom-2.492.x/pom.xml
  bom-2.504.x/pom.xml
  pom.xml
  sample-plugin/pom.xml
Labels: developer, full-test
